// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV5AUigsLt8scbCtg6m1LAWA1UaDZCCfM',
    appId: '1:272750034054:web:c75c5e5476749e29d62507',
    messagingSenderId: '272750034054',
    projectId: 'used-mobil-phone',
    authDomain: 'used-mobil-phone.firebaseapp.com',
    storageBucket: 'used-mobil-phone.firebasestorage.app',
    measurementId: 'G-39SVDEZ6NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALQjKEnevAMWW8zmb0Nh4MEar6TPvzuEA',
    appId: '1:272750034054:android:90e0ce456dfe94f0d62507',
    messagingSenderId: '272750034054',
    projectId: 'used-mobil-phone',
    storageBucket: 'used-mobil-phone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDbKADf6kWqB7CXyNWWMflxSyySvFl0no',
    appId: '1:272750034054:ios:1d1914f85cfd8bd8d62507',
    messagingSenderId: '272750034054',
    projectId: 'used-mobil-phone',
    storageBucket: 'used-mobil-phone.firebasestorage.app',
    iosBundleId: 'com.example.mobileShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDbKADf6kWqB7CXyNWWMflxSyySvFl0no',
    appId: '1:272750034054:ios:1d1914f85cfd8bd8d62507',
    messagingSenderId: '272750034054',
    projectId: 'used-mobil-phone',
    storageBucket: 'used-mobil-phone.firebasestorage.app',
    iosBundleId: 'com.example.mobileShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV5AUigsLt8scbCtg6m1LAWA1UaDZCCfM',
    appId: '1:272750034054:web:b2df6667e525cc53d62507',
    messagingSenderId: '272750034054',
    projectId: 'used-mobil-phone',
    authDomain: 'used-mobil-phone.firebaseapp.com',
    storageBucket: 'used-mobil-phone.firebasestorage.app',
    measurementId: 'G-PXQ3Q3LJZT',
  );
}
